logging:
  level:
    org:
      springframework: info

server:
  port: 8080  #default port

spring:
  application:
    name: persistence-task
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        jdbc:
          batch_size: 20
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true